# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "a7adf7c7f49e548059ac9c65d6c344d1d6571daf"

[[deps.FingerTrees]]
path = "."
uuid = "3d24749a-0845-4c16-a2f2-051d7e3c7003"
version = "0.1.0"
